<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Prelude.fs" />
    <Compile Include="Noise.fs" />
    <Compile Include="MathEx.fs" />
    <Compile Include="Domain.fs" />
    <Compile Include="Tuning.fs" />
    <Compile Include="ProcGen/Materials.fs" />
    <Compile Include="ProcGen/MeshGen.fs" />
    <Compile Include="ProcGen/Guns.fs" />
    <Compile Include="ProcGen/AudioSynth.fs" />
    <Compile Include="ProcGen/FontGen.fs" />
    <Compile Include="ProcGen/Humanoid.fs" />
    <Compile Include="ProcGen/LevelDsl.fs" />
    <Compile Include="ProcGen/LevelCompile.fs" />
    <Compile Include="ProcGen/MapFile.fs" />
    <Compile Include="Maps/Paintball.fs" />
    <Compile Include="Maps/ScrapDepot.fs" />
    <Compile Include="Maps/CanalYard.fs" />
    <Compile Include="Maps/TrainingYard.fs" />
    <Compile Include="Maps/OmahaDraw.fs" />
    <Compile Include="ProcGen/Levels.fs" />
    <Compile Include="Movement.fs" />
    <Compile Include="Weapons.fs" />
    <Compile Include="Ballistics.fs" />
    <Compile Include="SpecialProjectiles.fs" />
    <Compile Include="Grenades.fs" />
    <Compile Include="Damage.fs" />
    <Compile Include="Perception.fs" />
    <Compile Include="AiBrain.fs" />
    <Compile Include="Multiplayer.fs" />
    <Compile Include="Script.fs" />
    <Compile Include="Sim.fs" />
  </ItemGroup>
</Project>
